sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          input_type: text
          antlers: false
          display: 'Site Name'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          width: 50
      -
        handle: logo
        field:
          mode: list
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Logo
          type: assets
          icon: assets
          width: 50
          listable: hidden
          instructions_position: above
      -
        handle: social
        field:
          fields:
            -
              handle: name
              field:
                input_type: text
                antlers: false
                display: Name
                type: text
                icon: text
                width: 33
                listable: hidden
                instructions_position: above
            -
              handle: url
              field:
                input_type: text
                antlers: false
                display: URL
                type: text
                icon: text
                width: 33
                listable: hidden
                instructions_position: above
            -
              handle: icon
              field:
                mode: list
                restrict: false
                allow_uploads: false
                show_filename: true
                max_files: 1
                display: Icon
                type: assets
                icon: assets
                width: 33
                listable: hidden
                instructions_position: above
          mode: table
          reorderable: true
          display: Social
          type: grid
          icon: grid
          instructions: 'Set any social media links'
          listable: hidden
          instructions_position: above
